import { Jost } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import AppNavbar from "@/src/layout/AppNavbar";

const inter = Jost({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${inter.className} flex flex-col justify-center items-center overflow-x-hidden pb-12`}
        >
          <AppNavbar />

          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
